import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <div className="flex flex-col h-screen">
          <header className="h-16 bg-black text-white">
            <div className="container mx-auto flex items-center justify-center h-full">
              <h1 className="text-lg font-bold">Gemini APIを利用したチャットアプリ</h1>
            </div>
          </header>
          <main className="flex-grow overflow-hidden">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}