FROM node:20-bullseye-slim

# FROM node:20-bullseye-slim AS base

# WORKDIR /app

# COPY package.json ./
# COPY package-lock.json ./
# RUN nom install

# COPY . .

# RUN npm run build

# ENV NEXT_TELEMETRY_DISABLED=1

# CMD ["npm", "start"]
